#!/usr/bin/env python3
"""Write an index.md into every documents folder.

An agent that needs last week's report has two options: grep the whole tree, or
read one small file that says what is where. The second is cheaper and gets more
accurate as the folder grows - grep degrades exactly when you have enough
material for it to matter.

Each index lists the folder's documents with their title, date, and first line,
plus links to subfolders. Plain relative-link markdown, so it reads correctly in
any editor and doubles as an Obsidian vault index if you point Obsidian here.

Usage:
    python3 scripts/index.py           # index the configured documents dirs
    python3 scripts/index.py PATH ...  # index specific folders
"""
import os
import re
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jarvis_config  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER = "<!-- generated by `jarvis index` - edits are overwritten -->"
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".obsidian", ".venv"}
MAX_DEPTH = 4
# Folder furniture: navigation, labels, and shape examples. Not documents, and
# not listed as such. Mirrors isFolderMeta() in server.js - keep the two in step.
META_FILES = {"index.md", "readme.md", "claude.md"}


def is_folder_meta(name):
    n = name.lower()
    return n in META_FILES or re.search(r"\.example\.(md|txt)$", n) is not None


load_config = jarvis_config.load
expand = jarvis_config.expand


def summarize(path):
    """Title, date, kind, status, and a one-line gist, from frontmatter first."""
    title = os.path.splitext(os.path.basename(path))[0]
    date = ""
    kind = ""
    status = ""
    gist = ""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            head = f.read(4000)
    except Exception:
        return title, date, kind, status, gist

    # YAML frontmatter, if present
    fm = re.match(r"^---\n(.*?)\n---", head, re.S)
    body = head[fm.end():] if fm else head
    if fm:
        for line in fm.group(1).split("\n"):
            m = re.match(r"\s*(title|date|kind|status)\s*:\s*(.+)", line, re.I)
            if not m:
                continue
            key, val = m.group(1).lower(), m.group(2).strip().strip("\"'")
            if key == "title":
                title = val
            elif key == "date":
                date = val
            elif key == "kind":
                kind = val
            elif key == "status":
                status = val

    for line in body.split("\n"):
        s = line.strip()
        if not s:
            continue
        if s.startswith("#"):
            if not fm:
                title = s.lstrip("#").strip() or title
            continue
        if s.startswith(("---", "<!--", "|", "```")):
            continue
        gist = re.sub(r"[*_`\[\]]", "", s)[:110]
        break

    if not date:
        m = re.search(r"(20\d{2}-\d{2}-\d{2})", os.path.basename(path))
        date = m.group(1) if m else datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d")
    if not kind:
        m = re.match(r"20\d{2}-\d{2}-\d{2}-([a-z0-9]+)", os.path.basename(path))
        kind = m.group(1) if m else ""
    return title, date, kind, status, gist


def index_folder(folder, depth=0):
    """Write folder/index.md; recurse into subfolders. Returns files indexed."""
    if depth > MAX_DEPTH or not os.path.isdir(folder):
        return 0

    try:
        entries = sorted(os.listdir(folder))
    except PermissionError:
        return 0

    docs, subdirs = [], []
    for name in entries:
        if name.startswith(".") or name in SKIP_DIRS:
            continue
        full = os.path.join(folder, name)
        if os.path.isdir(full):
            subdirs.append(name)
        elif name.lower().endswith((".md", ".txt")) and not is_folder_meta(name):
            docs.append(name)

    count = 0
    for sub in subdirs:
        count += index_folder(os.path.join(folder, sub), depth + 1)

    # nothing here and nothing below - do not litter an empty index
    if not docs and not subdirs:
        return count

    rows = []
    for name in docs:
        title, date, kind, status, gist = summarize(os.path.join(folder, name))
        rows.append((date, title, name, kind, status, gist))
    rows.sort(key=lambda r: r[0], reverse=True)

    label = os.path.basename(folder.rstrip("/")) or folder
    out = [
        MARKER,
        f"# {label}",
        "",
        f"{len(rows)} document{'s' if len(rows) != 1 else ''}"
        + (f", {len(subdirs)} subfolder{'s' if len(subdirs) != 1 else ''}" if subdirs else "")
        + f". Updated {datetime.now().strftime('%Y-%m-%d %H:%M')}.",
        "",
    ]

    if subdirs:
        out += ["## Subfolders", ""]
        out += [f"- [{s}/]({s}/index.md)" for s in subdirs]
        out += [""]

    if rows:
        out += ["## Documents", ""]
        for date, title, name, kind, status, gist in rows:
            tags = []
            if kind:
                tags.append(f"`{kind}`")
            # only flag a status worth acting on; "final" is the norm and adds noise
            if status and status.lower() not in ("final", "done", "published"):
                tags.append(f"**{status.upper()}**")
            line = f"- **{date}** {' '.join(tags)} [{title}]({name})".replace("  ", " ")
            if gist:
                line += f" — {gist}"
            out.append(line)
        out += [""]

    with open(os.path.join(folder, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    return count + len(rows)


def main():
    targets = sys.argv[1:]
    if not targets:
        cfg = load_config()
        targets = [
            os.path.join(ROOT, "reports"),
            os.path.join(ROOT, "drafts"),
            expand(cfg.get("journal", {}).get("dir")) or os.path.join(ROOT, "journal"),
            *[expand(d) for d in cfg.get("documents_dirs", [])],
            *[expand(d) for d in cfg.get("knowledge", {}).get("context_dirs", [])],
        ]

    # reports/ and journal/ file by month, so each YYYY-MM folder is indexed
    # too - otherwise the parent index lists directories and no documents.
    months = []
    for t in targets:
        real = os.path.realpath(expand(t))
        if not os.path.isdir(real):
            continue
        for name in os.listdir(real):
            if re.fullmatch(r"\d{4}-\d{2}", name) and os.path.isdir(os.path.join(real, name)):
                months.append(os.path.join(real, name))
    targets = targets + months

    seen, total, touched = set(), 0, 0
    for t in targets:
        real = os.path.realpath(expand(t))
        if real in seen or not os.path.isdir(real):
            continue
        seen.add(real)
        n = index_folder(real)
        if n:
            touched += 1
            total += n
            print(f"{real}: {n} documents")

    print(f"indexed {total} documents across {touched} tree(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
